
services:
  upstat_backend:
    build: ./api/common
    ports:
      - "8080:8080"
    env_file:
      - ./api/common/.env
    networks:
      - mynetwork

  envoy:
    image: envoyproxy/envoy:v1.31-latest
    ports:
      - "8081:8081"
      - "9901:9901"
    volumes:
      - ./deploy/envoy/envoy.yaml:/etc/envoy/envoy.yaml:ro
    depends_on:
      - upstat_backend
    networks:
      - mynetwork

  app-frontend:
    build:
      context: ./App
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./App:/app
    depends_on:
      - upstat_backend

networks:
  mynetwork:
    driver: bridge
